---
kind: pipeline
type: kubernetes
name: npm_mongo_1.4.1

## Secrets in use
# NPM_TOKEN: Token with read rights to @nbeyer/* repositories and publish for this repo
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# AWS_DEFAULT_REGION

trigger:
  event:
    - push

steps:
  - name: restore-cache-with-key
    image: meltwater/drone-cache:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION:
        from_secret: AWS_DEFAULT_REGION
    settings:
      restore: true
      bucket: beyer.dev.cache
      region: AWS_DEFAULT_REGION
      archive_format: "gzip"
      cache_key: '{{ .Repo.Name }}'
      mount:
        - 'node_modules'

  - name: build
    image: 095565711062.dkr.ecr.eu-west-1.amazonaws.com/beyer.dev.drone:node18-aws
    commands:
      - node -v
      - npm -v
      - tsc -v
      - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm i
      - git add package-lock.json && git commit -m "package-lock [CI SKIP]" || true
      - tsc
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN

  - name: unittest
    image: 095565711062.dkr.ecr.eu-west-1.amazonaws.com/beyer.dev.drone:node18-aws
    commands:
      - npm test
    environment:
      MONGO_URL: mongodb://mongo/
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_OUTPUT: json
      AWS_DEFAULT_REGION:
        from_secret: AWS_DEFAULT_REGION

  - name: publish
    image: 095565711062.dkr.ecr.eu-west-1.amazonaws.com/beyer.dev.drone:node18-aws
    commands:
      - npm config set //registry.npmjs.org/:_authToken $NPM_PUBLISH_TOKEN
      - git config user.email $DRONE_COMMIT_AUTHOR_EMAIL
      - git config user.name $DRONE_COMMIT_AUTHOR
      - PKG_NAME="$(jq -r '.name' package.json)"
      - npm version patch -m "%s Commit by $DRONE_COMMIT_AUTHOR $DRONE_COMMIT_SHA $DRONE_COMMIT_MESSAGE [CI SKIP]"
      - npm publish
      - git push --follow-tags --set-upstream origin master
    environment:
      NPM_PUBLISH_TOKEN:
        from_secret: NPM_TOKEN
      DRONE_COMMIT_AUTHOR: $DRONE_COMMIT_AUTHOR
      DRONE_COMMIT_AUTHOR_EMAIL: $DRONE_COMMIT_AUTHOR_EMAIL
      DRONE_COMMIT_SHA: $DRONE_COMMIT_SHA
      DRONE_COMMIT_MESSAGE: $DRONE_COMMIT_MESSAGE
    when:
      branch:
        - master

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION:
        from_secret: AWS_DEFAULT_REGION
    settings:
      rebuild: true
      bucket: beyer.dev.cache
      region: AWS_DEFAULT_REGION
      archive_format: "gzip"
      cache_key: '{{ .Repo.Name }}'
      mount:
        - 'node_modules'

services:
  - name: mongo
    image: mongo:4.2



---
kind: signature
hmac: dd77c7226a9cd079a8df798abc60b843478a84d04aebe1336538e41a977bfca7

...
