---
kind: pipeline
name: npm_mongo_1.3.0

## Secrets in use
# NPM_PUBLISH_TOKEN: Token with publish rights on repository for project
# NPM_TOKEN: Token with read rights to @nbeyer/* repositories
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

trigger:
  event:
    - push

steps:
  - name: build
    image: 095565711062.dkr.ecr.eu-west-1.amazonaws.com/beyer.dev.drone:node12.x
    commands:
      - node -v
      - npm -v
      - tsc -v
      - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm i
      - tsc
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN

  - name: unittest
    image: 095565711062.dkr.ecr.eu-west-1.amazonaws.com/beyer.dev.drone:node12.x
    commands:
      - npm test
    environment:
      MONGO_URL: mongodb://mongo/
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_OUTPUT: json
      AWS_DEFAULT_REGION: eu-west-1

  - name: publish
    image: 095565711062.dkr.ecr.eu-west-1.amazonaws.com/beyer.dev.drone:node12.x
    commands:
      - npm config set //registry.npmjs.org/:_authToken $NPM_PUBLISH_TOKEN
      - PKG_NAME="$(jq -r '.name' package.json)"
      - PKG_VERSION="$(jq -r '.version' package.json)"
      - PGK_VERSION_MAJOR="$(echo $PKG_VERSION | cut -d '.' -f1)"
      - PGK_VERSION_MINOR="$(echo $PKG_VERSION | cut -d '.' -f2)"
      - NPM_VERSION="$(npm view $PKG_NAME version)"
      - NPM_VERSION_MAJOR="$(echo $NPM_VERSION | cut -d '.' -f1)"
      - NPM_VERSION_MINOR="$(echo $NPM_VERSION | cut -d '.' -f2)"
      - if (($NPM_VERSION != $PKG_VERSION)); then npm version --no-git-tag-version --allow-same-version $NPM_VERSION && git add package*.json && git commit; fi
      - if (($PGK_VERSION_MAJOR > $NPM_VERSION_MAJOR)); then METHOD="major"; elif (($PGK_VERSION_MINOR > $NPM_VERSION_MINOR)); then METHOD="minor"; else METHOD="patch"; fi
      - npm version $METHOD -m "%s Commit by $DRONE_COMMIT_AUTHOR $DRONE_COMMIT_SHA $DRONE_COMMIT_MESSAGE [CI SKIP]"
      - npm publish
      - PKG_VERSION="$(npm view $PKG_NAME version)"
      - git config user.email $DRONE_COMMIT_AUTHOR_EMAIL
      - git config user.name $DRONE_COMMIT_AUTHOR
      - git tag -m "Commit by $DRONE_COMMIT_AUTHOR $DRONE_COMMIT_MESSAGE $DRONE_COMMIT_SHA" -a $PKG_VERSION $DRONE_COMMIT_SHA
      - git push --follow-tags --set-upstream origin master
    environment:
      NPM_PUBLISH_TOKEN:
        from_secret: NPM_PUBLISH_TOKEN
      DRONE_COMMIT_AUTHOR: $DRONE_COMMIT_AUTHOR
      DRONE_COMMIT_AUTHOR_EMAIL: $DRONE_COMMIT_AUTHOR_EMAIL
      DRONE_COMMIT_SHA: $DRONE_COMMIT_SHA
      DRONE_COMMIT_MESSAGE: $DRONE_COMMIT_MESSAGE
    when:
      branch:
        - master

services:
  - name: mongo
    image: mongo:4.2



---
kind: signature
hmac: 5754bab16354cf04d68d79e231bdb58fc8ebe27e1fd268a40e0d9d8f2dafa497

...
